# This workflow will transer backend repo code to the ec2 machine,
# the ec2 machine where code will be deploy is use to serve backend for web application
# When there is a push to the "main" branch in "server" repo this workflow will run.
#
# I have used custom ec2 as a github action runner for this repo. i have configured
# that ec2 for specific task to run as a github action runner.
#
# In BACKEND ec2 instance nginx, node js is pre-installed.

name: Deploy backend code to backend server
on:
  # activates the workflow when there is a push on the main branch
  #push:
   # branches:
    #  - main
    #paths:  
     # - 'server/**'
  workflow_dispatch:
     
jobs:
  deploy-code-in-backend-server:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: present working directory
        run: pwd
      -
        name: list all items
        run: ls
      -
        name: cat dockerfile
        run: cat Dockerfile
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./server/
          push: true
          tags: divyapatel42/ecommerce-webapp:backendGithubActions
      - name: multiple command
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 65.0.173.69
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            ls
            docker rmi -f divyapatel42/ecommerce-webapp:backendGithubActions 2>/dev/null
            docker rm -f $(docker ps -q --filter "publish=8000/tcp") 2>/dev/null
            docker run -d -p 8000:8000 divyapatel42/ecommerce-webapp:backendGithubActions
          
