# This workflow will transer backend repo code to the ec2 machine,
# the ec2 machine where code will be deploy is use to serve backend for web application
# When there is a push to the "main" branch in "server" repo this workflow will run.
#
# I have used custom ec2 as a github action runner for this repo. i have configured
# that ec2 for specific task to run as a github action runner.
#
# In BACKEND ec2 instance nginx, node js is pre-installed.

name: Deploy backend code to backend server
on:
  # activates the workflow when there is a push on the main branch
  #push:
   # branches:
    #  - main
    #paths:  
     # - 'server/**'
  workflow_dispatch:
     
jobs:
  deploy-code-in-backend-server:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: divyapatel42/ecommerce-webapp:backendGithubActions
      #- run: |
       #   rsync -avz --progress --delete -e ssh /home/ubuntu/actions-runner/_work/react-node-project/react-node-project/server  ubuntu@15.206.27.102:~/backenddata
        #  ssh ubuntu@15.206.27.102
         # cd ~/backenddata
          #npm start
          #sudo systemctl restart nginx
