name: Running Self Hosed Runner
on:
  # activates the workflow when there is a push on the main branch
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@v3
      - name: Print echo
        run: |
          echo "Hello Bro"
          ls
          pwd
        
        
