name: Running Self Hosed Runner
on:
  # activates the workflow when there is a push on the main branch
  push:
    branches:
      - main
     
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" 
      - run: npm install
      - run: npm run build

      - name: rsync deployments
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: build/
          remote_path: /var/www/html/
          remote_host: ec2-13-233-19-64.ap-south-1.compute.amazonaws.com
          remote_user: ubuntu
          remote_key: ${{ secrets.PRIVATE_KEY }}
