name: Running Self Hosed Runner
on:
  # activates the workflow when there is a push on the main branch
  push:
    branches:
      - main
    paths:  
      - 'client/**'
     
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Print echo
        run: |
          echo "Hello Bro"
          pwd
          cd 
          touch puu2.txt
        
        
