name: Running Self Hosed Runner
on:
  # activates the workflow when there is a push on the main branch
  push:
    branches:
      - main
    paths:  
      - 'client/**'
  workflow_dispatch:
     
jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" 
      - run: pwd
      - run: npm install
      - run: npm run build

      - run: |
          rsync -avz --progress -e ssh /home/ubuntu/actions-runner/_work/react-node-project/react-node-project/client/build  ubuntu@13.233.19.64:/tempdata
