# This workflow will transer frontend repo build to the ec2 machine,
# the ec2 machine where build will be deploy is use to serve frontend for web application
# When there is a push to the "main" branch in "client" repo this workflow will run.
#
# I have used custom ec2 as a github action runner for this repo. i have configured
# that ec2 for specific task to run as a github action runner.
#
# In FRONTEND ec2 instance nginx, node js is pre-installed.
name: Deploy frontend build to frontend server
on:
  # activates the workflow when there is a push on the main branch
 # push:
  #  branches:
   #   - main
    #paths:  
     # - 'client/**'
  workflow_dispatch:
     
jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" 
      - run: pwd
      - run: npm install
      - run: npm run build

      - run: |
          rsync -avz --progress --delete -e ssh /home/ubuntu/actions-runner/_work/react-node-project/react-node-project/client/build  ubuntu@13.233.19.64:~/var/www/build/
          ssh -t ubuntu@13.233.19.64
          sudo systemctl restart nginx
