name: Build and Deploy with Artifact Sharing

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create status file
        run: |
          echo "success" > deployment_status.txt 

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: deployment_status.txt  # Replace with the path to your build output

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This job depends on the build job

    steps:
      - uses: actions/checkout@v3

      - name: Download build artifact from previous job
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: downloaded_build/  # Download and save in "downloaded_build" directory

      - name: Show Artifact (using downloaded artifact)
        run:  cd downloaded_build/ && ls # Adapt based on your deployment script

